env:
  global:
    - CC_TEST_REPORTER_ID=71aa371b4a5b3cf5f1c75adc853afc89a19dd66808fc1e4ca1fbed8e7a2355a9
sudo: required

language: bash

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
services:
  - docker

before_install:
  - docker build -t unoconv-promise:latest .

script:
  - docker run unoconv-promise:latest npm run test:report

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
